version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: leave-mgt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: leave_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - leave-mgt-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leave-mgt-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/leave_management
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysql
    networks:
      - leave-mgt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leave-mgt-frontend
    ports:
      - "8080:80" # Use 8080 on host to avoid port 80 conflict
    depends_on:
      - backend
    networks:
      - leave-mgt-network

volumes:
  mysql_data:

networks:
  leave-mgt-network:
    driver: bridge
